# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create([
  {username: 'User1'},
  {username: 'User2'},
  {username: 'User3'},
  {username: 'User4'},
  {username: 'User5'},
  {username: 'User6'},
  {username: 'User7'},
  {username: 'User8'},
  {username: 'User9'},
  {username: 'User10'},
  {username: 'User11'},
  {username: 'User12'},
  {username: 'User13'},
  {username: 'User14'},
  {username: 'User15'},
  {username: 'User16'},
  {username: 'User17'},
  {username: 'User18'},
  {username: 'User19'},
  {username: 'User20'},
])

Poll.create([
  {title: 'Poll1', user_id: 1},
  {title: 'Poll2', user_id: 1},
  {title: 'Poll3', user_id: 1},
  {title: 'Poll4', user_id: 2},
  {title: 'Poll5', user_id: 2},
  {title: 'Poll6', user_id: 2},
  {title: 'Poll7', user_id: 3},
  {title: 'Poll8', user_id: 3},
  {title: 'Poll9', user_id: 3},
  {title: 'Poll10', user_id: 4},
  {title: 'Poll11', user_id: 4},
  {title: 'Poll12', user_id: 4},
  {title: 'Poll13', user_id: 5},
  {title: 'Poll14', user_id: 5},
  {title: 'Poll15', user_id: 5},
  {title: 'Poll16', user_id: 6},
  {title: 'Poll17', user_id: 6},
  {title: 'Poll18', user_id: 6},
  {title: 'Poll19', user_id: 7},
  {title: 'Poll20', user_id: 7},
])

Question.create([
  {text: "What does '1' mean?", poll_id: 1},
  {text: "What does '2' mean?", poll_id: 2},
  {text: "What does '3' mean?", poll_id: 3},
  {text: "What does '4' mean?", poll_id: 4},
  {text: "What does '5' mean?", poll_id: 5},
  {text: "What does '6' mean?", poll_id: 6},
  {text: "What does '7' mean?", poll_id: 7},
  {text: "What does '8' mean?", poll_id: 8},
  {text: "What does '9' mean?", poll_id: 9},
  {text: "What does '10' mean?", poll_id: 10},
  {text: "What does '11' mean?", poll_id: 11},
  {text: "What does '12' mean?", poll_id: 12},
  {text: "What does '13' mean?", poll_id: 13},
  {text: "What does '14' mean?", poll_id: 14},
  {text: "What does '15' mean?", poll_id: 15},
  {text: "What does '16' mean?", poll_id: 16},
  {text: "What does '17' mean?", poll_id: 17},
  {text: "What does '18' mean?", poll_id: 18},
  {text: "What does '19' mean?", poll_id: 19},
  {text: "What does '20' mean?", poll_id: 20},
])

AnswerChoice.create([
  {text: 'Must mean something 1.', question_id: 1},
  {text: 'Must mean something 2.', question_id: 1},
  {text: 'Must mean something 3.', question_id: 1},
  {text: 'Must mean something 1.', question_id: 2},
  {text: 'Must mean something 2.', question_id: 2},
  {text: 'Must mean something 3.', question_id: 2},
  {text: 'Must mean something 1.', question_id: 3},
  {text: 'Must mean something 2.', question_id: 3},
  {text: 'Must mean something 3.', question_id: 3},
  {text: 'Must mean something 1.', question_id: 4},
  {text: 'Must mean something 2.', question_id: 4},
  {text: 'Must mean something 3.', question_id: 4},
  {text: 'Must mean something 1.', question_id: 5},
  {text: 'Must mean something 2.', question_id: 5},
  {text: 'Must mean something 3.', question_id: 5},
  {text: 'Must mean something 1.', question_id: 6},
  {text: 'Must mean something 2.', question_id: 6},
  {text: 'Must mean something 3.', question_id: 6},
  {text: 'Must mean something 1.', question_id: 7},
  {text: 'Must mean something 2.', question_id: 7},
  {text: 'Must mean something 3.', question_id: 7},
  {text: 'Must mean something 1.', question_id: 8},
  {text: 'Must mean something 2.', question_id: 8},
  {text: 'Must mean something 3.', question_id: 8},
  {text: 'Must mean something 1.', question_id: 9},
  {text: 'Must mean something 2.', question_id: 9},
  {text: 'Must mean something 3.', question_id: 9},
  {text: 'Must mean something 1.', question_id: 10},
  {text: 'Must mean something 2.', question_id: 10},
  {text: 'Must mean something 3.', question_id: 10},
  {text: 'Must mean something 1.', question_id: 11},
  {text: 'Must mean something 2.', question_id: 11},
  {text: 'Must mean something 3.', question_id: 11},
  {text: 'Must mean something 1.', question_id: 12},
  {text: 'Must mean something 2.', question_id: 12},
  {text: 'Must mean something 3.', question_id: 12},
  {text: 'Must mean something 1.', question_id: 13},
  {text: 'Must mean something 2.', question_id: 13},
  {text: 'Must mean something 3.', question_id: 13},
  {text: 'Must mean something 1.', question_id: 14},
  {text: 'Must mean something 2.', question_id: 14},
  {text: 'Must mean something 3.', question_id: 14},
  {text: 'Must mean something 1.', question_id: 15},
  {text: 'Must mean something 2.', question_id: 15},
  {text: 'Must mean something 3.', question_id: 15},
  {text: 'Must mean something 1.', question_id: 16},
  {text: 'Must mean something 2.', question_id: 16},
  {text: 'Must mean something 3.', question_id: 16},
  {text: 'Must mean something 1.', question_id: 17},
  {text: 'Must mean something 2.', question_id: 17},
  {text: 'Must mean something 3.', question_id: 17},
  {text: 'Must mean something 1.', question_id: 18},
  {text: 'Must mean something 2.', question_id: 18},
  {text: 'Must mean something 3.', question_id: 18},
  {text: 'Must mean something 1.', question_id: 19},
  {text: 'Must mean something 2.', question_id: 19},
  {text: 'Must mean something 3.', question_id: 19},
  {text: 'Must mean something 1.', question_id: 20},
  {text: 'Must mean something 2.', question_id: 20},
  {text: 'Must mean something 3.', question_id: 20},
])

Response.create([
  {user_id: 10, answer_choice_id: 1},
  {user_id: 10, answer_choice_id: 4},
  {user_id: 10, answer_choice_id: 7},
  {user_id: 10, answer_choice_id: 10},
  {user_id: 10, answer_choice_id: 13},
  {user_id: 10, answer_choice_id: 16},
  {user_id: 10, answer_choice_id: 19},
  {user_id: 10, answer_choice_id: 22},
  {user_id: 10, answer_choice_id: 25},
  {user_id: 10, answer_choice_id: 28},
  {user_id: 10, answer_choice_id: 31},
  {user_id: 10, answer_choice_id: 34},
  {user_id: 10, answer_choice_id: 37},
  {user_id: 10, answer_choice_id: 40},
  {user_id: 10, answer_choice_id: 43},
  {user_id: 10, answer_choice_id: 46},
  {user_id: 10, answer_choice_id: 49},
  {user_id: 10, answer_choice_id: 52},
  {user_id: 10, answer_choice_id: 55},
  {user_id: 10, answer_choice_id: 58},
  {user_id: 11, answer_choice_id: 1},
  {user_id: 11, answer_choice_id: 4},
  {user_id: 11, answer_choice_id: 7},
  {user_id: 11, answer_choice_id: 10},
  {user_id: 11, answer_choice_id: 13},
  {user_id: 11, answer_choice_id: 16},
  {user_id: 11, answer_choice_id: 19},
  {user_id: 11, answer_choice_id: 22},
  {user_id: 11, answer_choice_id: 25},
  {user_id: 11, answer_choice_id: 28},
  {user_id: 11, answer_choice_id: 31},
  {user_id: 11, answer_choice_id: 34},
  {user_id: 11, answer_choice_id: 37},
  {user_id: 11, answer_choice_id: 40},
  {user_id: 11, answer_choice_id: 43},
  {user_id: 11, answer_choice_id: 46},
  {user_id: 11, answer_choice_id: 49},
  {user_id: 11, answer_choice_id: 52},
  {user_id: 11, answer_choice_id: 55},
  {user_id: 11, answer_choice_id: 58},
  {user_id: 12, answer_choice_id: 1},
  {user_id: 12, answer_choice_id: 4},
  {user_id: 12, answer_choice_id: 7},
  {user_id: 12, answer_choice_id: 10},
  {user_id: 12, answer_choice_id: 13},
  {user_id: 12, answer_choice_id: 16},
  {user_id: 12, answer_choice_id: 19},
  {user_id: 12, answer_choice_id: 22},
  {user_id: 12, answer_choice_id: 25},
  {user_id: 12, answer_choice_id: 28},
  {user_id: 12, answer_choice_id: 31},
  {user_id: 12, answer_choice_id: 34},
  {user_id: 12, answer_choice_id: 37},
  {user_id: 12, answer_choice_id: 40},
  {user_id: 12, answer_choice_id: 43},
  {user_id: 12, answer_choice_id: 46},
  {user_id: 12, answer_choice_id: 49},
  {user_id: 12, answer_choice_id: 52},
  {user_id: 12, answer_choice_id: 55},
  {user_id: 12, answer_choice_id: 58},
  {user_id: 13, answer_choice_id: 1},
  {user_id: 13, answer_choice_id: 4},
  {user_id: 13, answer_choice_id: 7},
  {user_id: 13, answer_choice_id: 10},
  {user_id: 13, answer_choice_id: 13},
  {user_id: 13, answer_choice_id: 16},
  {user_id: 13, answer_choice_id: 19},
  {user_id: 13, answer_choice_id: 22},
  {user_id: 13, answer_choice_id: 25},
  {user_id: 13, answer_choice_id: 28},
  {user_id: 13, answer_choice_id: 31},
  {user_id: 13, answer_choice_id: 34},
  {user_id: 13, answer_choice_id: 37},
  {user_id: 13, answer_choice_id: 40},
  {user_id: 13, answer_choice_id: 43},
  {user_id: 13, answer_choice_id: 46},
  {user_id: 13, answer_choice_id: 49},
  {user_id: 13, answer_choice_id: 52},
  {user_id: 13, answer_choice_id: 55},
  {user_id: 13, answer_choice_id: 58},
  {user_id: 14, answer_choice_id: 1},
  {user_id: 14, answer_choice_id: 4},
  {user_id: 14, answer_choice_id: 7},
  {user_id: 14, answer_choice_id: 10},
  {user_id: 14, answer_choice_id: 13},
  {user_id: 14, answer_choice_id: 16},
  {user_id: 14, answer_choice_id: 19},
  {user_id: 14, answer_choice_id: 22},
  {user_id: 14, answer_choice_id: 25},
  {user_id: 14, answer_choice_id: 28},
  {user_id: 14, answer_choice_id: 31},
  {user_id: 14, answer_choice_id: 34},
  {user_id: 14, answer_choice_id: 37},
  {user_id: 14, answer_choice_id: 40},
  {user_id: 14, answer_choice_id: 43},
  {user_id: 14, answer_choice_id: 46},
  {user_id: 14, answer_choice_id: 49},
  {user_id: 14, answer_choice_id: 52},
  {user_id: 14, answer_choice_id: 55},
  {user_id: 14, answer_choice_id: 58},
  {user_id: 15, answer_choice_id: 2},
  {user_id: 15, answer_choice_id: 5},
  {user_id: 15, answer_choice_id: 8},
  {user_id: 15, answer_choice_id: 11},
  {user_id: 15, answer_choice_id: 14},
  {user_id: 15, answer_choice_id: 17},
  {user_id: 15, answer_choice_id: 20},
  {user_id: 15, answer_choice_id: 23},
  {user_id: 15, answer_choice_id: 26},
  {user_id: 15, answer_choice_id: 29},
  {user_id: 15, answer_choice_id: 32},
  {user_id: 15, answer_choice_id: 35},
  {user_id: 15, answer_choice_id: 38},
  {user_id: 15, answer_choice_id: 41},
  {user_id: 15, answer_choice_id: 44},
  {user_id: 15, answer_choice_id: 47},
  {user_id: 15, answer_choice_id: 50},
  {user_id: 15, answer_choice_id: 53},
  {user_id: 15, answer_choice_id: 56},
  {user_id: 15, answer_choice_id: 59},
  {user_id: 16, answer_choice_id: 2},
  {user_id: 16, answer_choice_id: 5},
  {user_id: 16, answer_choice_id: 8},
  {user_id: 16, answer_choice_id: 11},
  {user_id: 16, answer_choice_id: 14},
  {user_id: 16, answer_choice_id: 17},
  {user_id: 16, answer_choice_id: 20},
  {user_id: 16, answer_choice_id: 23},
  {user_id: 16, answer_choice_id: 26},
  {user_id: 16, answer_choice_id: 29},
  {user_id: 16, answer_choice_id: 32},
  {user_id: 16, answer_choice_id: 35},
  {user_id: 16, answer_choice_id: 38},
  {user_id: 16, answer_choice_id: 41},
  {user_id: 16, answer_choice_id: 44},
  {user_id: 16, answer_choice_id: 47},
  {user_id: 16, answer_choice_id: 50},
  {user_id: 16, answer_choice_id: 53},
  {user_id: 16, answer_choice_id: 56},
  {user_id: 16, answer_choice_id: 59},
  {user_id: 17, answer_choice_id: 3},
  {user_id: 17, answer_choice_id: 6},
  {user_id: 17, answer_choice_id: 9},
  {user_id: 17, answer_choice_id: 12},
  {user_id: 17, answer_choice_id: 15},
  {user_id: 17, answer_choice_id: 18},
  {user_id: 17, answer_choice_id: 21},
  {user_id: 17, answer_choice_id: 24},
  {user_id: 17, answer_choice_id: 27},
  {user_id: 17, answer_choice_id: 30},
  {user_id: 17, answer_choice_id: 33},
  {user_id: 17, answer_choice_id: 36},
  {user_id: 17, answer_choice_id: 39},
  {user_id: 17, answer_choice_id: 42},
  {user_id: 17, answer_choice_id: 45},
  {user_id: 17, answer_choice_id: 48},
  {user_id: 17, answer_choice_id: 51},
  {user_id: 17, answer_choice_id: 54},
  {user_id: 17, answer_choice_id: 57},
  {user_id: 17, answer_choice_id: 60},
])